### ISSUE TITLE
[Bug]: Module missing in Docker image

### ISSUE THREAD

**Issue by GonozalIX** [pangaea-data-publisher/fuji#454] opened 2023-11-13 10:45 UTC
The python module 'imp' is missing in the docker image for version 3.1.0

## Description
In the new docker image [3.1.0](https://github.com/orgs/pangaea-data-publisher/packages/container/fuji/146464808?tag=3.1.0) I get a _ModuleNotFoundError: No module named 'imp'_  on start.
On 3.0.0 everything still works as intended.

## Expected Behavior
A docker container with the image [3.1.0](https://github.com/orgs/pangaea-data-publisher/packages/container/fuji/146464808?tag=3.1.0)  should start.

## Actual Behavior
It's crashing.

## Possible Fix
I assume it's just missing while building the image

## Steps to reproduce
Run `docker run -d -p 1071:1071 ghcr.io/pangaea-data-publisher/fuji:3.1.0` and container will stop after 10s or so.

## Your Environment
Linux Mint 20.3
Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1

**Comment by afuetterer** [comment] 2023-11-24 18:47
This issue is caused by the update to Python 3.12 in the Docker image.

In Python 3.11 everything works fine.
But `pyRdfa` and `extruct` seem to be problematic.

```
ImportError while importing test module '.../fuji/tests/controllers/test_fair_check.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../.pyenv/versions/3.12.0/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/controllers/test_fair_check.py:3: in <module>
    from fuji_server.controllers.fair_check import FAIRCheck
fuji_server/controllers/fair_check.py:57: in <module>
    from fuji_server.harvester.metadata_harvester import MetadataHarvester
fuji_server/harvester/metadata_harvester.py:9: in <module>
    import extruct
.venv/fuji/lib/python3.12/site-packages/extruct/__init__.py:1: in <module>
    from ._extruct import SYNTAXES, extract
.venv/fuji/lib/python3.12/site-packages/extruct/_extruct.py:13: in <module>
    from extruct.rdfa import RDFaExtractor
.venv/fuji/lib/python3.12/site-packages/extruct/rdfa.py:16: in <module>
    from pyRdfa import Options
.venv/fuji/lib/python3.12/site-packages/pyRdfa/__init__.py:295: in <module>
    from .state            import ExecutionContext
.venv/fuji/lib/python3.12/site-packages/pyRdfa/state.py:39: in <module>
    from .utils         import quote_URI
.venv/fuji/lib/python3.12/site-packages/pyRdfa/utils.py:19: in <module>
    import os, os.path, sys, imp, datetime, socket
E   ModuleNotFoundError: No module named 'imp'
```

**Comment by afuetterer** [comment] 2024-01-03 10:56
@huberrob, you can close this one.

**Closed** 2024-01-03 11:39 UTC
Labels: bug

**Comment by afuetterer** [comment] 2024-01-05 17:40
@huberrob: You reintrocuded the breaking docker image. Maybe the dependabot should not send docker images udpates anymore?
