### ISSUE TITLE
FAIR assessment tool down

### ISSUE THREAD

**Issue by PipGrylls** [pangaea-data-publisher/fuji#506] opened 2024-06-11 09:32 UTC
The tool is giving the following error:

> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an > error in the application.

**Comment by huberrob** [comment] 2024-06-11 09:48
It should automatically restart , please wait a second

**Comment by PipGrylls** [comment] 2024-06-11 09:50
It’s been giving this error for a few hours for me and a collaborator said it was also down last week.

**Comment by huberrob** [comment] 2024-06-11 10:43
I just checked and it works, but of course the tool can break for different reasons. What dataset are you trying to test? Can you post a link her please?

**Comment by PipGrylls** [comment] 2024-06-12 10:54
Hi, 
The code we are trying to test is
https://github.com/paramm-team/pybamm-param

For me the tool is still broken
![Screenshot 2024-06-12 at 11 54 30](https://github.com/pangaea-data-publisher/fuji/assets/22835635/acb7ccfd-a8c2-461f-9450-6d93d3295e54)

**Comment by huberrob** [comment] 2024-06-12 11:31
Oh you did not mention you are using a local installation. Which version are you running?
I thought yo are using https://f-uji.net

**Comment by huberrob** [comment] 2024-06-12 11:59
I think you are on the right (FAIR) track, if you need more help please let me know

**Comment by PipGrylls** [comment] 2024-06-12 13:46
The one on f-uji.net is indeed working

**Comment by huberrob** [comment] 2024-06-12 14:19
Ok, I see they are using the software metrics, unfortunately I cannot reproduce the error, maybe @karacolada knows more about this?

**Comment by karacolada** [comment] 2024-06-13 13:36
Hi @PipGrylls, thanks for reporting this, it's a bug in our extension for FRSM. I reported it in an issue on our repo [here](https://github.com/softwaresaved/fuji/issues/39). I'm working on fixing it now so should be alright in a bit :)

@huberrob feal free to close this issue, we'll fix it on our side.

**Closed** 2024-06-14 08:56 UTC
